/*
 * A3BU_PCB1.h
 *
 * Header file for use with A3BU_PCB1 board
 * (8 LEDs, 5 joystick-like buttons, 3 switches, 1 encoder)
 */ 

#ifndef A3BU_PCB1_H_INCLUDED
#define A3BU_PCB1_H_INCLUDED

#include "gpio/gpio.h"

#ifdef A3BU_PCB1_CON1J2_CON2J1
	#undef A3BU_PCB1_CON1J1_CON2J2
#else
	#define A3BU_PCB1_CON1J1_CON2J2
#endif

// Port definition

#if defined( A3BU_PCB1_CON1J1_CON2J2 )

	#define PCB1_SW_BUT_PORT		PORTC
	#define PCB1_SW_BUT_PORT_LO		PORTC
	#define PCB1_SW_BUT_PORT_HI		PORTC
	#define PCB1_LED1234_PORT		PORTA
	#define PCB1_LED5678_PORT		PORTB

#elif defined( A3BU_PCB1_CON1J2_CON2J1 )

	#define PCB1_SW_BUT_PORT_LO		PORTB
	#define PCB1_SW_BUT_PORT_HI		PORTA
	#define PCB1_LED1234_PORT		PORTC
	#define PCB1_LED5678_PORT		PORTC

#endif

// Pin definition

#define PCB1_SW1_PIN			GPIO_PIN_0
#define PCB1_SW2_PIN			GPIO_PIN_1
#define PCB1_SW3_PIN			GPIO_PIN_2
#define PCB1_BUT_LEFT_PIN		GPIO_PIN_3
#define PCB1_BUT_UP_PIN			GPIO_PIN_4
#define PCB1_BUT_CENTER_PIN		GPIO_PIN_5
#define PCB1_BUT_RIGHT_PIN		GPIO_PIN_6
#define PCB1_BUT_DOWN_PIN		GPIO_PIN_7
#define PCB1_SW_PINS			(PCB1_SW1_PIN | PCB1_SW2_PIN | PCB1_SW3_PIN)
#define PCB1_BUT_PINS			(PCB1_BUT_LEFT_PIN | PCB1_BUT_UP_PIN | PCB1_BUT_CENTER_PIN | PCB1_BUT_RIGHT_PIN | PCB1_BUT_DOWN_PIN)

#define PCB1_SW_BUT_PIN_LO		(PCB1_SW1_PIN | PCB1_SW2_PIN | PCB1_SW3_PIN | PCB1_BUT_LEFT_PIN)
#define PCB1_SW_BUT_PIN_HI		(PCB1_BUT_UP_PIN | PCB1_BUT_CENTER_PIN | PCB1_BUT_RIGHT_PIN | PCB1_BUT_DOWN_PIN)

#define PCB1_ENC1_PIN			PCB1_SW1_PIN
#define PCB1_ENC2_PIN			PCB1_SW2_PIN

#define PCB1_LED1_PIN			GPIO_PIN_7
#define PCB1_LED2_PIN			GPIO_PIN_6
#define PCB1_LED3_PIN			GPIO_PIN_5
#define PCB1_LED4_PIN			GPIO_PIN_4
#define PCB1_LED1234_PINS		(PCB1_LED1_PIN | PCB1_LED2_PIN | PCB1_LED3_PIN | PCB1_LED4_PIN)

#define PCB1_LED5_PIN			GPIO_PIN_3
#define PCB1_LED6_PIN			GPIO_PIN_2
#define PCB1_LED7_PIN			GPIO_PIN_1
#define PCB1_LED8_PIN			GPIO_PIN_0
#define PCB1_LED5678_PINS		(PCB1_LED5_PIN | PCB1_LED6_PIN | PCB1_LED7_PIN | PCB1_LED8_PIN)

#endif /* A3BU_PCB1_H_INCLUDED */
